[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
# Needed for ESP-IDF
rustflags = [
    # "-C", "link-arg=-Wl,-Tlink.x",  <-- REMOVED
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-Wl,-zstack-size=65536",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32"
